# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wavelet_canvas = MplWidget(self.centralwidget)
        self.wavelet_canvas.setObjectName("wavelet_canvas")
        self.horizontalLayout_5.addWidget(self.wavelet_canvas)
        self.hodograph_canvas = MplWidget(self.centralwidget)
        self.hodograph_canvas.setObjectName("hodograph_canvas")
        self.horizontalLayout_5.addWidget(self.hodograph_canvas)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.file_to_load_from_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.file_to_load_from_line_edit.setText("")
        self.file_to_load_from_line_edit.setObjectName("file_to_load_from_line_edit")
        self.verticalLayout_4.addWidget(self.file_to_load_from_line_edit)
        self.file_to_save_to_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.file_to_save_to_line_edit.setText("")
        self.file_to_save_to_line_edit.setObjectName("file_to_save_to_line_edit")
        self.verticalLayout_4.addWidget(self.file_to_save_to_line_edit)
        self.lower_altitude_bound_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_altitude_bound_line_edit.setText("")
        self.lower_altitude_bound_line_edit.setObjectName("lower_altitude_bound_line_edit")
        self.verticalLayout_4.addWidget(self.lower_altitude_bound_line_edit)
        self.upper_altitude_bound_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_altitude_bound_line_edit.setText("")
        self.upper_altitude_bound_line_edit.setObjectName("upper_altitude_bound_line_edit")
        self.verticalLayout_4.addWidget(self.upper_altitude_bound_line_edit)
        self.lower_scale_bound_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_scale_bound_line_edit.setText("")
        self.lower_scale_bound_line_edit.setObjectName("lower_scale_bound_line_edit")
        self.verticalLayout_4.addWidget(self.lower_scale_bound_line_edit)
        self.upper_scale_bound_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_scale_bound_line_edit.setText("")
        self.upper_scale_bound_line_edit.setObjectName("upper_scale_bound_line_edit")
        self.verticalLayout_4.addWidget(self.upper_scale_bound_line_edit)
        self.start_analysis_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_analysis_button.setObjectName("start_analysis_button")
        self.verticalLayout_4.addWidget(self.start_analysis_button)
        self.plot_altitude_window_button = QtWidgets.QPushButton(self.centralwidget)
        self.plot_altitude_window_button.setObjectName("plot_altitude_window_button")
        self.verticalLayout_4.addWidget(self.plot_altitude_window_button)
        self.display_quarter_max_power_surface_button = QtWidgets.QPushButton(self.centralwidget)
        self.display_quarter_max_power_surface_button.setObjectName("display_quarter_max_power_surface_button")
        self.verticalLayout_4.addWidget(self.display_quarter_max_power_surface_button)
        self.plot_hodograph_from_detransformed_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.plot_hodograph_from_detransformed_data_button.setObjectName("plot_hodograph_from_detransformed_data_button")
        self.verticalLayout_4.addWidget(self.plot_hodograph_from_detransformed_data_button)
        self.get_gravity_wave_params_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_gravity_wave_params_button.setObjectName("get_gravity_wave_params_button")
        self.verticalLayout_4.addWidget(self.get_gravity_wave_params_button)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lower_altitude_bound_hodo_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_altitude_bound_hodo_line_edit.setText("")
        self.lower_altitude_bound_hodo_line_edit.setObjectName("lower_altitude_bound_hodo_line_edit")
        self.verticalLayout_5.addWidget(self.lower_altitude_bound_hodo_line_edit)
        self.upper_altitude_bound_hodo_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_altitude_bound_hodo_line_edit.setText("")
        self.upper_altitude_bound_hodo_line_edit.setObjectName("upper_altitude_bound_hodo_line_edit")
        self.verticalLayout_5.addWidget(self.upper_altitude_bound_hodo_line_edit)
        self.plot_hodograph_altitude_window_button = QtWidgets.QPushButton(self.centralwidget)
        self.plot_hodograph_altitude_window_button.setObjectName("plot_hodograph_altitude_window_button")
        self.verticalLayout_5.addWidget(self.plot_hodograph_altitude_window_button)
        self.fit_ellipses_to_wind_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.fit_ellipses_to_wind_data_button.setObjectName("fit_ellipses_to_wind_data_button")
        self.verticalLayout_5.addWidget(self.fit_ellipses_to_wind_data_button)
        self.save_gravity_wave_params_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_gravity_wave_params_button.setObjectName("save_gravity_wave_params_button")
        self.verticalLayout_5.addWidget(self.save_gravity_wave_params_button)
        self.save_method_1_cbox = QtWidgets.QCheckBox(self.centralwidget)
        self.save_method_1_cbox.setObjectName("save_method_1_cbox")
        self.verticalLayout_5.addWidget(self.save_method_1_cbox)
        self.save_method_2_cbox = QtWidgets.QCheckBox(self.centralwidget)
        self.save_method_2_cbox.setObjectName("save_method_2_cbox")
        self.verticalLayout_5.addWidget(self.save_method_2_cbox)
        self.show_me_where_i_am = QtWidgets.QCheckBox(self.centralwidget)
        self.show_me_where_i_am.setObjectName("show_me_where_i_am")
        self.verticalLayout_5.addWidget(self.show_me_where_i_am)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_to_load_from_line_edit.setPlaceholderText(_translate("MainWindow", "Filename to load from"))
        self.file_to_save_to_line_edit.setPlaceholderText(_translate("MainWindow", "File to save to"))
        self.lower_altitude_bound_line_edit.setPlaceholderText(_translate("MainWindow", "Lower altitude bound (km)"))
        self.upper_altitude_bound_line_edit.setPlaceholderText(_translate("MainWindow", "Upper altitude bound (km)"))
        self.lower_scale_bound_line_edit.setPlaceholderText(_translate("MainWindow", "Lower scale bound"))
        self.upper_scale_bound_line_edit.setPlaceholderText(_translate("MainWindow", "Upper scale bound"))
        self.start_analysis_button.setWhatsThis(_translate("MainWindow", "Loads data from file and displays entire power spectrum"))
        self.start_analysis_button.setText(_translate("MainWindow", "Start analysis"))
        self.plot_altitude_window_button.setText(_translate("MainWindow", "Plot altitude window"))
        self.display_quarter_max_power_surface_button.setText(_translate("MainWindow", "Display quarter max "))
        self.plot_hodograph_from_detransformed_data_button.setText(_translate("MainWindow", "Plot hodograph from de-transformed quarter max data"))
        self.get_gravity_wave_params_button.setWhatsThis(_translate("MainWindow", "Power surface window acceptable?"))
        self.get_gravity_wave_params_button.setText(_translate("MainWindow", "Get gravity wave parameters (Stokes and Hodograph)"))
        self.lower_altitude_bound_hodo_line_edit.setPlaceholderText(_translate("MainWindow", "Lower altitude bound (km)"))
        self.upper_altitude_bound_hodo_line_edit.setPlaceholderText(_translate("MainWindow", "Upper altitude bound (km)"))
        self.plot_hodograph_altitude_window_button.setText(_translate("MainWindow", "Plot hodograph from altitude range"))
        self.fit_ellipses_to_wind_data_button.setText(_translate("MainWindow", "Fit ellipses to hodograph and return parameters"))
        self.save_gravity_wave_params_button.setText(_translate("MainWindow", "Save gravity wave params"))
        self.save_method_1_cbox.setText(_translate("MainWindow", "Save method 1 ellipse fit"))
        self.save_method_2_cbox.setText(_translate("MainWindow", "Save method 2 ellipse fit"))
        self.show_me_where_i_am.setText(_translate("MainWindow", "Show me where I am"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

